### PR TITLE
Build System Fixes and GDASApp Test Relocation

### LINKED ISSUE #14: Add tests for the netcdf/non-bufr to ioda converters

### LINKED ISSUE #15: The build of the RTOFS converters fails
Missing a header file:
```c++
#include <cstdint>
```

### LINKED ISSUE #16: The spoc # is not correct
It's currently pointing to a commit that contains only a licence file. We should probably point to `develop`?

### LINKED ISSUE #19: Add GitHub Actions Workflow for Build and CI Tests on GitHub Runner

### PR DESCRIPTION
**Pull request by guillaumevernieres**
- fixes #16 (... I think)
- fixes #15 
- fixes #14 
- fixes #19

### CODE REVIEW

File: utils/test/prepdata.sh [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+# test/soca/gw/setup_obsproc.sh for test_gdasapp_soca_setup_obsproc
+
+# TODO: It needs to point to experimental obs instead of prepdata.sh
+# Get the machine hostname
+MACHINE_NAME=$(hostname)
+
+# Check if the machine name is "hera"
+if [[ "$MACHINE_NAME" =~ ^hfe0[1-9]$ || "$MACHINE_NAME" =~ ^hfe1[01]$ ]]; then
+    echo "Running on hera, loading anaconda modules."
+    module use -a /contrib/anaconda/modulefiles
```
Comment (CoryMartin-NOAA) [inline utils/test/prepdata.sh:12]: I know this was a blind copy, but should we be using this? do we have what we need in the obsforge modulefile?

Comment (guillaumevernieres) [reply utils/test/prepdata.sh:12]: This might be related to an `ncgen` issue we had at some point. @apchoiCMD , do you remember why we did this?

Comment (apchoiCMD) [reply utils/test/prepdata.sh:12]: @guillaumevernieres yes, that comes from  `ncgen` issue and I want to test it again while this is new PR-

Comment (givelberg) [reply utils/test/prepdata.sh:12]: This is probably not related,  I just built obsforge on hercules. The module load command loads the default modules for wcoss2 instead of the hercules.intel
At the moment I'm trying to run the prepoceanobs code with obsforge, but no success yet.

Comment (guillaumevernieres) [reply utils/test/prepdata.sh:12]: > This is probably not related, I just built obsforge on hercules. The module load command loads the default modules for wcoss2 instead of the hercules.intel At the moment I'm trying to run the prepoceanobs code with obsforge, but no success yet.

Is this what you did:
```
module use modulefiles
module load obsforge/hercules.intel
```
?

Comment (apchoiCMD) [reply utils/test/prepdata.sh:12]: > This is probably not related, I just built obsforge on hercules. The module load command loads the default modules for wcoss2 instead of the hercules.intel At the moment I'm trying to run the prepoceanobs code with obsforge, but no success yet.

Have you run this ctest? We do not know until running it through ctests!

Comment (givelberg) [reply utils/test/prepdata.sh:12]: @guillaumevernieres I did what you wrote and it works. 
The module load obsforge loads the wcoss2 module file by default. I.e. the machine is not recognized automatically.
@apchoiCMD I haven't run the ctest yet.

Comment (givelberg) [reply utils/test/prepdata.sh:12]: I had to add
wxflowPYpath="${OBSFORGEHOME}/sorc/wxflow/src"
PYTHONPATH="${wxflowPYpath}:${PYTHONPATH}"
export PYTHONPATH
without this it was picking up an incorrect version of wxflow from outside of obsForge and causing a bug.

Comment (guillaumevernieres) [reply utils/test/prepdata.sh:12]: @givelberg , is your comment above related to this PR?

Comment (guillaumevernieres) [reply utils/test/prepdata.sh:12]: I'm marking this as `resolved`, the answer is yes for now @CoryMartin-NOAA .

Comment (CoryMartin-NOAA) [reply utils/test/prepdata.sh:12]: @givelberg I just ran the build script on hercules and it found the correct system name/modules automatically?
```
hercules-login-2:/work/noaa/da/cmartin/mar2025/obsforge$ ./build.sh 
Building obsForge on hercules
```

**Comment by givelberg** [comment]
I just built on orion and had the same problem.



(eva) ***@***.*** obsForge]$ module load obsforge

Lmod has detected the following error:  The following module(s) are

unknown: "openjpeg/2.5.0" "gettext/0.19.7" "git-lfs/2.11.0"


Please check the spelling or version number. Also try "module spider ..."

It is also possible your cache file is out-of-date; it may help to try:

  $ module --ignore_cache load "openjpeg/2.5.0" "gettext/0.19.7"

"git-lfs/2.11.0"


Also make sure that all modulefiles written in TCL start with the string

#%Module


Executing this command requires loading "cmake/3.23.1" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "gettext/0.19.7" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "pcre2/10.42" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "curl/8.4.0" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "git-lfs/2.11.0" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "netcdf-fortran/4.6.1" which failed

while processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "nco/5.0.6" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "boost/1.83.0" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "openjpeg/2.5.0" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "openblas/0.3.24" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.luaExecuting
this command requires loading "esmf/8.5.0" which failed while

processing the following module(s):


    Module fullname        Module Filename

    ---------------        ---------------

    obsforge/wcoss2.intel
/work/noaa/da/edwardg/03182025/obsForge/modulefiles/obsforge/wcoss2.intel.lua



(eva) ***@***.*** obsForge]$ ls modulefiles/obsforge/

total 40

4 ./                4 hera.intel.lua       4 orion.intel.lua

4 ../               4 hercules.gnu.lua     4 wcoss2.intel.lua

4 gaeac5.intel.lua  4 hercules.intel.lua

4 gaeac6.intel.lua  4 noaacloud.intel.lua

This worked:

(eva) ***@***.*** obsForge]$ module load obsforge/orion.intel

-------------------------------------------------------------------------------

The following dependent module(s) are not currently loaded: py-numpy/1.22.3
(required by: bufr/12.0.1), python/3.10.13 (required by: boost/1.83.0,
bufr/12.0.1, fckit/0.11.0, atlas/0.35.1, py-pybind11/2.11.0)

-------------------------------------------------------------------------------

**Comment by guillaumevernieres** [comment]
tadaa-ci
:tada:

File: utils/preproc/applications/CMakeLists.txt [hunk 2]
```diff
@@ -8,7 +8,11 @@ ecbuild_add_executable( TARGET obsforge_obsprovider2ioda.x
...
+target_link_libraries( obsforge_obsprovider2ioda.x PUBLIC oops ioda netcdf2ioda NetCDF::NetCDF_CXX)
 
-link_directories(${CMAKE_SOURCE_DIR}/rtofs)
-target_link_libraries(obsforge_obsprovider2ioda.x PRIVATE rtofs)
+# Set the RPATH to the build directory
+set_target_properties(obsforge_obsprovider2ioda.x PROPERTIES
+    BUILD_WITH_INSTALL_RPATH TRUE
+    INSTALL_RPATH "${CMAKE_BINARY_DIR}/lib"
+    INSTALL_RPATH_USE_LINK_PATH TRUE
+)
```
Comment (CoryMartin-NOAA) [inline utils/preproc/applications/CMakeLists.txt:18]: Missing EOL

File: utils/test/CMakeLists.txt [hunk 3]
```diff
@@ -0,0 +1,193 @@
...
+
+# copy rtofs binary input files to the testing area
+# and generate the tests
+
+set(RTOFS_INPUT_FILE1 "rtofsinsitu_2024032600.profile")
+set(RTOFS_INPUT_FILE2 "rtofsinsitu_2024032700.profile")
+
+# rtofs directory on orion:
+set(RTOFS_FILES_PATH
+	"/work/noaa/da/marineda/gfs-marine/data/obs/ci/obs"
```
Comment (CoryMartin-NOAA) [inline utils/test/CMakeLists.txt:90]: This should be set by env variable in the modulefiles

**Comment by apchoiCMD** [comment]
From `Hercules` Machine
```
(gdasapp) (gdasapp) hercules-login-4[76] mindoc$ ctest
Test project /work2/noaa/da/mchoi3/obsForge/build/obsforge-utils
      Start  1: test_obsforge_util_coding_norms
 1/13 Test  #1: test_obsforge_util_coding_norms ......   Passed    2.86 sec
      Start  2: test_obsforge_util_prepdata
 2/13 Test  #2: test_obsforge_util_prepdata ..........   Passed    6.20 sec
      Start  3: test_obsforge_util_rads2ioda
 3/13 Test  #3: test_obsforge_util_rads2ioda .........   Passed    5.94 sec
      Start  4: test_obsforge_util_ghrsst2ioda
 4/13 Test  #4: test_obsforge_util_ghrsst2ioda .......   Passed    0.08 sec
      Start  5: test_obsforge_util_rtofstmp
 5/13 Test  #5: test_obsforge_util_rtofstmp ..........   Passed    1.41 sec
      Start  6: test_obsforge_util_rtofssal
 6/13 Test  #6: test_obsforge_util_rtofssal ..........   Passed    1.15 sec
      Start  7: test_obsforge_util_smap2ioda
 7/13 Test  #7: test_obsforge_util_smap2ioda .........   Passed    0.08 sec
      Start  8: test_obsforge_util_smos2ioda
 8/13 Test  #8: test_obsforge_util_smos2ioda .........   Passed    0.08 sec
      Start  9: test_obsforge_util_viirsaod2ioda
 9/13 Test  #9: test_obsforge_util_viirsaod2ioda .....   Passed    0.35 sec
      Start 10: test_obsforge_util_icecamsr2ioda
10/13 Test #10: test_obsforge_util_icecamsr2ioda .....   Passed    0.36 sec
      Start 11: test_obsforge_util_icecmirs2ioda
11/13 Test #11: test_obsforge_util_icecmirs2ioda .....   Passed    0.08 sec
      Start 12: test_obsforge_util_icecjpssrr2ioda
12/13 Test #12: test_obsforge_util_icecjpssrr2ioda ...   Passed    0.08 sec
      Start 13: test_obsforge_util_insituall2ioda
13/13 Test #13: test_obsforge_util_insituall2ioda ....   Passed    0.08 sec

100% tests passed, 0 tests failed out of 13

Label Time Summary:
obsforge-utils    =  18.76 sec*proc (13 tests)
script            =  18.76 sec*proc (13 tests)

Total Test time (real) =  18.78 sec
```

File: utils/test/CMakeLists.txt (hunk 3 above)
Comment (guillaumevernieres) [reply utils/test/CMakeLists.txt:90]: Thanks @CoryMartin-NOAA , created an issue for this.

**Review by CoryMartin-NOAA — APPROVED** [review]
